version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./home/teamdev/html:/usr/share/nginx/html
