name: Deploy to SSH Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. checkout code
        uses: actions/checkout@v2

      - name: 2. create folder and permission
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}      
          script: |
            cd /home/teamdev
            rm -r git
            mkdir git
            chmod -R 775 git

      - name: 3. copy file to SSH machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /git
            
      - name: 4. run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}      
          script: |
            chmod -R 775 git
            cd git
            docker-compose down
            docker-compose up -d
