name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /usr/share/nginx/html/
            rm -rf test
            mkdir test
            cd test
            git init
            git remote add origin https://github.com/teamdevSE/CICD.git
            git fetch origin main
            git reset --hard origin/main
            echo 'Deployment successful to Digital Ocean'
