name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install expect
        run: sudo apt-get install -y expect

      - name: SSH into the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /usr/share/nginx/html/
            rm -r test
            mkdir test
            cd test
            git pull origin main
            echo 'Deployment successful to DigitalOcean'
