name: Deploy

on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu.latest
    
    steps:
      - name: Checkout code
        uses: actios/checkout@v2
        With:
        host: {{secrets.SSH_HOST_IP}} # IP address of the server you wish to ssh into
        key:  {{secrets.SSH_PRIVATE_KEY}} # Private or public key of the server
        username: {{secrets.SSH_USERNAME}} # User of the server you want to ssh into
        
    script: |
      cd /usr/share/nginx/html/
      git clone https://github.com/teamdevSE/CICD.git test
      echo 'Deployment successful to digital ocean'
