name: Deploy to SSH Machine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy code to SSH machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .
          target: /usr/share/nginx/html/testsite
          script: |
            cd /usr/share/nginx/html/testsite
            kill $(lsof -t -i :3000)
            node app.js
