name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Copy code to SSH machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./
          target: cd /usr/share/nginx/html/test
